### ISSUE TITLE
Cleaner variable management

### ISSUE THREAD

**Issue by liupeirong** [liupeirong/MLOpsManufacturing#41]
Review the [variable management article](https://github.com/liupeirong/MLOpsManufacturing/blob/main/docs/variable-management.md) and the image-classification-tensorflow sample to see if there're any additional guidelines or code that can be improved.

**Comment by h2floh** [comment]
## Glossary
| Term | Remark |
| --------------- | --------------- | 
| variables | here variable and parameters used in and for the CI/CD part as well for AML wrapper and business logic |

## Scenario or use case

There are many variables used in any Azure Machine Learning (AML) projects, including variables for Azure resources, Azure DevOps (ADO) pipelines, AML experiments and more. There are also many different ways to store them, for example, in environment variables, ADO variable templates, ADO variable groups, or supply them directly in command line. What's the best practice to manage these variables - which variables should be store where?

[more details](https://github.com/liupeirong/MLOpsManufacturing/blob/main/docs/variable-management.md)

**The v-team removed some variables from [the current samples](https://github.com/liupeirong/MLOpsManufacturing/blob/e41474298466766d6e866d4177cb361ac99449a4/samples/image-classification-tensorflow/ml_service/pipelines/build_data_processing_pipeline.py#L65) because they didn't felt maintainable or helpful**

**The project teams developed more feasible approaches then what the common staring point MLOpsPython provided**

Regarding variables to specify targeted compute environments this is related to #47 

## Acceptance criteria

- [ ] Best Practice [documentation](https://github.com/liupeirong/MLOpsManufacturing/tree/main/docs) around what values need to be stored in variables, where to store them, where to to the cut (maybe referencing one or several samples for demonstration of pros/cons?)

## Stretch Goal

- [ ] One [sample](https://github.com/liupeirong/MLOpsManufacturing/tree/main/samples) which leverages App Configuration Service (ACS can reference KeyVault for secrets internally) in favor of AzDO Variable Groups (just an idea see #19)
