### ISSUE TITLE
Tool to tag and search Azure ML Datasets

### ISSUE THREAD

**Issue by liupeirong** [liupeirong/MLOpsManufacturing#46]

**Comment by h2floh** [comment]
## Glossary
| Term | Remark |
| --------------- | --------------- | 
| tag | a AML dataset can get attributed with [tags](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.abstract_dataset.abstractdataset?view=azure-ml-py#add-tags-tags-none-), not to confuse with [labels](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-use-labeled-dataset) for image datasets |

## Scenario or use case

For tracking of used datasets within the automated processing of data, model creation and deployment (intermediate) datasets need to be tagged with metainformation about data quality, content, run in which they were generated and other data to identify or exclude them as candidates for a training run or for a easier review if quality of the model is not as expected. While adding metadata to the dataset is easy, it turns out that searching for datasets via metadata is not. Tools and guidance should be provided in order to do so.

**The project teams created a tool to do so.**

## Acceptance criteria

- [ ] Search Tool (jupyter notebook?) provided in the `common` [section](https://github.com/liupeirong/MLOpsManufacturing/tree/main/common)
- [ ] [Documentation](https://github.com/liupeirong/MLOpsManufacturing/tree/main/docs) how to connect and use the tool, best practice for good metadata candidates to tag
- [ ] One [sample](https://github.com/liupeirong/MLOpsManufacturing/tree/main/samples) should tag datasets that it can be used in the documentation to demonstrate the tool usage.

## Stretch Goal

- [ ] Search Tool as vscode plugin (just an idea)
